/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DIDRegistry__factory } from "./DIDRegistry__factory";
export { VCRegistry__factory } from "./VCRegistry__factory";
