FROM node:20-alpine AS builder
WORKDIR /app

# Install dependencies and build frontend
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build:frontend

FROM nginx:stable-alpine
COPY --from=builder /app/dist/frontend /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
