/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DIDRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "controllerDIDs"
      | "deactivateDID"
      | "dids"
      | "getDIDsByController"
      | "isDIDActive"
      | "registerDID"
      | "resolveDID"
      | "updateDID"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DIDDeactivated" | "DIDRegistered" | "DIDUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "controllerDIDs",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateDID",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "dids", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getDIDsByController",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isDIDActive", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerDID",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "resolveDID", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateDID",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "controllerDIDs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateDID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dids", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDIDsByController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDIDActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolveDID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateDID", data: BytesLike): Result;
}

export namespace DIDDeactivatedEvent {
  export type InputTuple = [did: string, timestamp: BigNumberish];
  export type OutputTuple = [did: string, timestamp: bigint];
  export interface OutputObject {
    did: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DIDRegisteredEvent {
  export type InputTuple = [
    did: string,
    controller: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    did: string,
    controller: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    did: string;
    controller: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DIDUpdatedEvent {
  export type InputTuple = [did: string, timestamp: BigNumberish];
  export type OutputTuple = [did: string, timestamp: bigint];
  export interface OutputObject {
    did: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DIDRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DIDRegistry;
  waitForDeployment(): Promise<this>;

  interface: DIDRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  controllerDIDs: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  deactivateDID: TypedContractMethod<[did: string], [void], "nonpayable">;

  dids: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean, bigint, bigint] & {
        didString: string;
        publicKeyHex: string;
        controller: string;
        active: boolean;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  getDIDsByController: TypedContractMethod<
    [controller: AddressLike],
    [string[]],
    "view"
  >;

  isDIDActive: TypedContractMethod<[did: string], [boolean], "view">;

  registerDID: TypedContractMethod<
    [did: string, publicKeyHex: string],
    [void],
    "nonpayable"
  >;

  resolveDID: TypedContractMethod<
    [did: string],
    [
      [string, string, string, boolean, bigint, bigint] & {
        didString: string;
        publicKeyHex: string;
        controller: string;
        active: boolean;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  updateDID: TypedContractMethod<
    [did: string, newPublicKeyHex: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "controllerDIDs"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateDID"
  ): TypedContractMethod<[did: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dids"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean, bigint, bigint] & {
        didString: string;
        publicKeyHex: string;
        controller: string;
        active: boolean;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDIDsByController"
  ): TypedContractMethod<[controller: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isDIDActive"
  ): TypedContractMethod<[did: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerDID"
  ): TypedContractMethod<
    [did: string, publicKeyHex: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDID"
  ): TypedContractMethod<
    [did: string],
    [
      [string, string, string, boolean, bigint, bigint] & {
        didString: string;
        publicKeyHex: string;
        controller: string;
        active: boolean;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateDID"
  ): TypedContractMethod<
    [did: string, newPublicKeyHex: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DIDDeactivated"
  ): TypedContractEvent<
    DIDDeactivatedEvent.InputTuple,
    DIDDeactivatedEvent.OutputTuple,
    DIDDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "DIDRegistered"
  ): TypedContractEvent<
    DIDRegisteredEvent.InputTuple,
    DIDRegisteredEvent.OutputTuple,
    DIDRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DIDUpdated"
  ): TypedContractEvent<
    DIDUpdatedEvent.InputTuple,
    DIDUpdatedEvent.OutputTuple,
    DIDUpdatedEvent.OutputObject
  >;

  filters: {
    "DIDDeactivated(string,uint256)": TypedContractEvent<
      DIDDeactivatedEvent.InputTuple,
      DIDDeactivatedEvent.OutputTuple,
      DIDDeactivatedEvent.OutputObject
    >;
    DIDDeactivated: TypedContractEvent<
      DIDDeactivatedEvent.InputTuple,
      DIDDeactivatedEvent.OutputTuple,
      DIDDeactivatedEvent.OutputObject
    >;

    "DIDRegistered(string,address,uint256)": TypedContractEvent<
      DIDRegisteredEvent.InputTuple,
      DIDRegisteredEvent.OutputTuple,
      DIDRegisteredEvent.OutputObject
    >;
    DIDRegistered: TypedContractEvent<
      DIDRegisteredEvent.InputTuple,
      DIDRegisteredEvent.OutputTuple,
      DIDRegisteredEvent.OutputObject
    >;

    "DIDUpdated(string,uint256)": TypedContractEvent<
      DIDUpdatedEvent.InputTuple,
      DIDUpdatedEvent.OutputTuple,
      DIDUpdatedEvent.OutputObject
    >;
    DIDUpdated: TypedContractEvent<
      DIDUpdatedEvent.InputTuple,
      DIDUpdatedEvent.OutputTuple,
      DIDUpdatedEvent.OutputObject
    >;
  };
}
