/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface VCRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "credentials"
      | "getVC"
      | "getVCsByIssuer"
      | "holderCredentials"
      | "isRevoked"
      | "issueVC"
      | "issuerCredentials"
      | "revokeVC"
      | "verifyVC"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "VCIssued" | "VCRevoked"): EventFragment;

  encodeFunctionData(functionFragment: "credentials", values: [string]): string;
  encodeFunctionData(functionFragment: "getVC", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getVCsByIssuer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "holderCredentials",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isRevoked", values: [string]): string;
  encodeFunctionData(
    functionFragment: "issueVC",
    values: [string, BytesLike, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "issuerCredentials",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "revokeVC", values: [string]): string;
  encodeFunctionData(
    functionFragment: "verifyVC",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "credentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVCsByIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "holderCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isRevoked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "issueVC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issuerCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeVC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyVC", data: BytesLike): Result;
}

export namespace VCIssuedEvent {
  export type InputTuple = [
    vcId: string,
    issuerDid: string,
    holderDid: string,
    vcHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vcId: string,
    issuerDid: string,
    holderDid: string,
    vcHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    vcId: string;
    issuerDid: string;
    holderDid: string;
    vcHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VCRevokedEvent {
  export type InputTuple = [
    vcId: string,
    revokedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vcId: string,
    revokedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    vcId: string;
    revokedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VCRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): VCRegistry;
  waitForDeployment(): Promise<this>;

  interface: VCRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  credentials: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, bigint, bigint, boolean, string] & {
        vcHash: string;
        issuerDid: string;
        holderDid: string;
        credentialType: string;
        issuedAt: bigint;
        expiresAt: bigint;
        revoked: boolean;
        issuerAddress: string;
      }
    ],
    "view"
  >;

  getVC: TypedContractMethod<
    [vcId: string],
    [
      [string, string, string, string, bigint, bigint, boolean] & {
        vcHash: string;
        issuerDid: string;
        holderDid: string;
        credentialType: string;
        issuedAt: bigint;
        expiresAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  getVCsByIssuer: TypedContractMethod<[issuerDid: string], [string[]], "view">;

  holderCredentials: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [string],
    "view"
  >;

  isRevoked: TypedContractMethod<[vcId: string], [boolean], "view">;

  issueVC: TypedContractMethod<
    [
      vcId: string,
      vcHash: BytesLike,
      issuerDid: string,
      holderDid: string,
      credentialType: string,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  issuerCredentials: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [string],
    "view"
  >;

  revokeVC: TypedContractMethod<[vcId: string], [void], "nonpayable">;

  verifyVC: TypedContractMethod<
    [vcId: string, vcHash: BytesLike],
    [
      [boolean, boolean, boolean, boolean] & {
        hashValid: boolean;
        isRevoked: boolean;
        isExpired: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "credentials"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, bigint, bigint, boolean, string] & {
        vcHash: string;
        issuerDid: string;
        holderDid: string;
        credentialType: string;
        issuedAt: bigint;
        expiresAt: bigint;
        revoked: boolean;
        issuerAddress: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVC"
  ): TypedContractMethod<
    [vcId: string],
    [
      [string, string, string, string, bigint, bigint, boolean] & {
        vcHash: string;
        issuerDid: string;
        holderDid: string;
        credentialType: string;
        issuedAt: bigint;
        expiresAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVCsByIssuer"
  ): TypedContractMethod<[issuerDid: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "holderCredentials"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "isRevoked"
  ): TypedContractMethod<[vcId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "issueVC"
  ): TypedContractMethod<
    [
      vcId: string,
      vcHash: BytesLike,
      issuerDid: string,
      holderDid: string,
      credentialType: string,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issuerCredentials"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "revokeVC"
  ): TypedContractMethod<[vcId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyVC"
  ): TypedContractMethod<
    [vcId: string, vcHash: BytesLike],
    [
      [boolean, boolean, boolean, boolean] & {
        hashValid: boolean;
        isRevoked: boolean;
        isExpired: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "VCIssued"
  ): TypedContractEvent<
    VCIssuedEvent.InputTuple,
    VCIssuedEvent.OutputTuple,
    VCIssuedEvent.OutputObject
  >;
  getEvent(
    key: "VCRevoked"
  ): TypedContractEvent<
    VCRevokedEvent.InputTuple,
    VCRevokedEvent.OutputTuple,
    VCRevokedEvent.OutputObject
  >;

  filters: {
    "VCIssued(string,string,string,bytes32,uint256)": TypedContractEvent<
      VCIssuedEvent.InputTuple,
      VCIssuedEvent.OutputTuple,
      VCIssuedEvent.OutputObject
    >;
    VCIssued: TypedContractEvent<
      VCIssuedEvent.InputTuple,
      VCIssuedEvent.OutputTuple,
      VCIssuedEvent.OutputObject
    >;

    "VCRevoked(string,address,uint256)": TypedContractEvent<
      VCRevokedEvent.InputTuple,
      VCRevokedEvent.OutputTuple,
      VCRevokedEvent.OutputObject
    >;
    VCRevoked: TypedContractEvent<
      VCRevokedEvent.InputTuple,
      VCRevokedEvent.OutputTuple,
      VCRevokedEvent.OutputObject
    >;
  };
}
