/**
 * Polygon smart contract deployment script
 * Run with: npx tsx src/contracts/deploy.ts
 *
 * Requires env vars:
 *   POLYGON_PRIVATE_KEY - deployer wallet private key
 *   POLYGON_RPC_URL     - RPC endpoint (Amoy testnet or mainnet)
 */
import { ethers } from 'ethers';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Compiled contract ABIs and bytecodes - these would normally come from compilation
// For demo purposes, we use interface-only deployment via ethers
// In production: use hardhat/foundry to compile and deploy

const DID_REGISTRY_ABI = [
  'function registerDID(string memory did, string memory publicKeyHex) external',
  'function updateDID(string memory did, string memory newPublicKeyHex) external',
  'function deactivateDID(string memory did) external',
  'function resolveDID(string memory did) external view returns (string, string, address, bool, uint256, uint256)',
  'function isDIDActive(string memory did) external view returns (bool)',
  'function getDIDsByController(address controller) external view returns (string[] memory)',
  'event DIDRegistered(string indexed did, address indexed controller, uint256 timestamp)',
  'event DIDDeactivated(string indexed did, uint256 timestamp)',
];

const VC_REGISTRY_ABI = [
  'function issueVC(string memory vcId, bytes32 vcHash, string memory issuerDid, string memory holderDid, string memory credentialType, uint256 expiresAt) external',
  'function revokeVC(string memory vcId) external',
  'function verifyVC(string memory vcId, bytes32 vcHash) external view returns (bool hashValid, bool isRevoked, bool isExpired, bool exists)',
  'function getVC(string memory vcId) external view returns (bytes32, string memory, string memory, string memory, uint256, uint256, bool)',
  'function getVCsByIssuer(string memory issuerDid) external view returns (string[] memory)',
  'function isRevoked(string memory vcId) external view returns (bool)',
  'event VCIssued(string indexed vcId, string indexed issuerDid, string indexed holderDid, bytes32 vcHash, uint256 timestamp)',
  'event VCRevoked(string indexed vcId, address indexed revokedBy, uint256 timestamp)',
];

export { DID_REGISTRY_ABI, VC_REGISTRY_ABI };

async function deploy() {
  const rpcUrl = process.env.POLYGON_RPC_URL;
  const privateKey = process.env.POLYGON_PRIVATE_KEY;

  if (!rpcUrl || !privateKey) {
    console.error('Missing POLYGON_RPC_URL or POLYGON_PRIVATE_KEY');
    process.exit(1);
  }

  const provider = new ethers.JsonRpcProvider(rpcUrl);
  const wallet = new ethers.Wallet(privateKey, provider);

  console.log('Deploying from:', wallet.address);
  console.log('Network:', (await provider.getNetwork()).name);

  // NOTE: These bytecodes need to be generated by compiling the Solidity contracts
  // with solc or hardhat. For now this script shows the deployment pattern.
  console.log('\nTo deploy contracts:');
  console.log('1. Install hardhat: npm install --save-dev hardhat @nomicfoundation/hardhat-ethers');
  console.log('2. npx hardhat compile');
  console.log('3. npx hardhat run scripts/deploy.js --network polygon_amoy');
  console.log('\nContract ABI files exported for use with existing deployed contracts.');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  deploy().catch(console.error);
}
