import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  const network = (await ethers.provider.getNetwork()).name;

  console.log(`\n━━━ Polygon Contract Deployment ━━━`);
  console.log(`Network : ${network}`);
  console.log(`Deployer: ${deployer.address}`);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log(`Balance : ${ethers.formatEther(balance)} MATIC`);

  if (balance === 0n) {
    const faucetUrl =
      network === "amoy"
        ? "https://faucet.polygon.technology"
        : "https://faucet.polygon.technology";
    throw new Error(
      `Deployer has 0 MATIC. Get testnet MATIC from: ${faucetUrl}`
    );
  }

  // ── Deploy DIDRegistry ──────────────────────────────────────────────────────
  console.log("\nDeploying DIDRegistry...");
  const DIDRegistry = await ethers.getContractFactory("DIDRegistry");
  const didRegistry = await DIDRegistry.deploy();
  await didRegistry.waitForDeployment();
  const didRegistryAddress = await didRegistry.getAddress();
  console.log(`  ✓ DIDRegistry deployed: ${didRegistryAddress}`);

  // ── Deploy VCRegistry ───────────────────────────────────────────────────────
  console.log("\nDeploying VCRegistry...");
  const VCRegistry = await ethers.getContractFactory("VCRegistry");
  const vcRegistry = await VCRegistry.deploy();
  await vcRegistry.waitForDeployment();
  const vcRegistryAddress = await vcRegistry.getAddress();
  console.log(`  ✓ VCRegistry deployed: ${vcRegistryAddress}`);

  // ── Write .env.blockchain ───────────────────────────────────────────────────
  const envContent = [
    `# Auto-generated by deploy-polygon.ts — ${new Date().toISOString()}`,
    `DID_REGISTRY_ADDRESS=${didRegistryAddress}`,
    `VC_REGISTRY_ADDRESS=${vcRegistryAddress}`,
    `POLYGON_NETWORK=${network}`,
    "",
  ].join("\n");

  const envPath = path.join(__dirname, "../.env.blockchain");
  fs.writeFileSync(envPath, envContent);
  console.log(`\n  ✓ Addresses saved to .env.blockchain`);

  // ── Summary ─────────────────────────────────────────────────────────────────
  console.log(`\n━━━ Deployment Complete ━━━`);
  console.log(`\nCopy these into your .env file:`);
  console.log(`  DID_REGISTRY_ADDRESS=${didRegistryAddress}`);
  console.log(`  VC_REGISTRY_ADDRESS=${vcRegistryAddress}`);
  console.log(`  POLYGON_NETWORK=${network}`);
  console.log(`\nThen restart the server — the sidebar will show "Live: ${network}"\n`);
}

main().catch((err) => {
  console.error("\n❌ Deployment failed:", err.message);
  process.exit(1);
});
